---
version: "3"
services:
 devopsdb:
   image: nagesh2devops/mynewapp:dbimage
   ports:
     - "3306:3306"
   deploy:
     replicas: 2

 application:
   image: nagesh2devops/mynewapp:appimage
   ports:
     - "1234:8080"
   deploy:
     replicas: 2 
   depends_on:
     - "devopsdb"
